name: Docs Crawler

on:
  push:
    branches:
      - main

jobs:
  docs-crawler:
    name: Run crawler for updating docs search
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the Crawler with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: aschmelyun/cleaver:latest
          options: -v ${{ github.workspace }}:/var/www
          run: |
              composer install
              npm install
              npm run production
              docker run -it --env API_KEY=${{ secrets.API_KEY }} --env APPLICATION_ID=${{ secrets.APPLICATION_ID }} -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper