name: Docs Crawler

on:
  push:
    branches:
      - main

jobs:
  docs-crawler:
    name: Run crawler for updating docs search
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the Crawler with Docker
        run: |
          docker run -t --rm \
          -e MEILISEARCH_HOST_URL=meilisearch-production-abff.up.railway.app/ \
          -e MEILISEARCH_API_KEY=${{ secrets.MEILISEARCH_API_KEY }} \
          -v ./config.json:/docs-scraper/config.json \ 
          getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json
