name: Docs Crawler

on:
  push:
    branches:
      - main

jobs:
  docs-crawler:
    name: Run crawler for updating docs search
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run the Crawler with Docker
        run: |
            docker run -it --env API_KEY=${{ secrets.API_KEY }} --env APPLICATION_ID=${{ secrets.APPLICATION_ID }} -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper